site_name: My Docs
nav :
    - Home : 
        - 'Le projet' : 'index.md'
    - 'User Guide' : 
        - 'Partie dessin' : 'use.md'
        - 'Partie sauvegarde' : 'save.md'
    - Fonctionnement : 
        - 'Fonctionnement de la partie dessin' : 'fonctionuse.md'
        - 'Fonctionnement de la partie sauvegarde' : 'fonctionsave.md'
theme: readthedocs
site_url: https://ajuton.gitlab.io
site_dir: public